service: grape-broker-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  httpApi:
    authorizers:
      auth0:
        type: jwt
        # TODO: We should have different audiences for each environment
        identitySource: $request.header.Authorization
        issuerUrl: https://grape-finance.us.auth0.com/
        audience:
          - https://grape.finance/api/auth

functions:
  grape-broker-api:
    handler: src/handler.entry
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
          authorizer:
            name: auth0

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.build.json"

plugins:
  - serverless-plugin-typescript

package:
  individually: true
  include:
    - "!*"
    - "!**"
    - src/*.ts
