service: grape-broker-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  grape-broker-api:
    handler: src/handler.entry
    events:
      - httpApi:
          path: /
          method: get
custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.build.json"

plugins:
  - serverless-plugin-typescript

package:
  individually: true
  include:
    - "!*"
    - "!**"
    - src/*.ts
