name: Lint

on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner."
      - name: Install Dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - run: echo "This job's status is ${{ job.status }}."
      - name: "Yamllint"
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: "./github"
          yamllint_strict: true
          yamllint_comment: false
